default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: weatherpop_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: weatherpop_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: weatherpop_production
  pool: 5
  timeout: 5000
